function mode2(){
 document.getElementById('header').style.background = '#fff',
 document.getElementById('anmy').style.background = '#fff',
 document.getElementById('fm2022').style.background = '#fff',
 document.getElementById('btnhome').style.background='#fff',
 document.querySelector('body').style.background= '#fff',
 document.querySelector('.solo').style.background=  '#ddd',
 document.getElementById('modhome1').style.background='#fff',
 document.getElementById('modhome2').style.background='#fff',
 document.querySelector('.put').style.background=  '#ddd',
 document.getElementById('puttext').style.color='#ff4500',
 document.querySelector('.social1').style.background=  '#fff',
 document.querySelector('.social2').style.background=  '#fff',
 document.querySelector('.social3').style.background=  '#fff',
 document.getElementById('movies1').style.background='#fff',
 document.querySelector('.back2').style.background=  '#fff',
 document.querySelector('.back3').style.background=  '#fff',
 document.querySelector('.back4').style.background=  '#fff',
 document.querySelector('.back5').style.background=  '#fff',
 document.querySelector('.back6').style.background=  '#fff',
 document.querySelector('.back7').style.background=  '#fff',
 document.querySelector('.back8').style.background=  '#fff',
 document.querySelector('.back9').style.background=  '#fff',
 document.querySelector('.back10').style.background=  '#fff',
 document.querySelector('.back11').style.background=  '#fff',
 document.querySelector('.back12').style.background=  '#fff',
 document.querySelector('.back13').style.background=  '#fff';

 }
function mode1(){
 document.getElementById('header').style.background = '#000',
 document.getElementById('anmy').style.background = '#000', 
 document.getElementById('fm2022').style.background = '#000',
 document.getElementById('btnhome').style.background='#000',
 document.querySelector('body').style.background= '#050505',
 document.querySelector('.solo').style.background=  '#000',
 document.getElementById('modhome1').style.background='#000',
 document.getElementById('modhome2').style.background='#000',
 document.querySelector('.put').style.background=  '#ff4500',
 document.getElementById('puttext').style.color='#000',
 document.querySelector('.social1').style.background=  '#000',
 document.querySelector('.social2').style.background=  '#000',
 document.querySelector('.social3').style.background=  '#000',
 document.getElementById('movies1').style.background='#000',
 document.querySelector('.back2').style.background=  '#000',
 document.querySelector('.back3').style.background=  '#000',
 document.querySelector('.back4').style.background=  '#000',
 document.querySelector('.back5').style.background=  '#000',
 document.querySelector('.back6').style.background=  '#000',
 document.querySelector('.back7').style.background=  '#000',
 document.querySelector('.back8').style.background=  '#000',
 document.querySelector('.back9').style.background=  '#000',
 document.querySelector('.back10').style.background=  '#000',
 document.querySelector('.back11').style.background=  '#000',
 document.querySelector('.back12').style.background=  '#000',
 document.querySelector('.back13').style.background=  '#000';
 }

 
